export const itemModels = {
  UPDATE_SRC: "UPDATE_SRC",

  REQUEST_ITEMS: "REQUEST_ITEMS",

  REQUEST_ITEMS_SUCCESS: "REQUEST_ITEMS_SUCCESS",
  REQUEST_ITEMS_ERROR: "REQUEST_ITEMS_ERROR",

  RECEIVE_ITEMS: "RECEIVE_ITEMS",
  RECEIVE_ITEMS_SUCCESS: "RECEIVE_ITEMS_SUCCESS",
  RECEIVE_ITEMS_ERROR: "RECEIVE_ITEMS_ERROR"
};
